//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuTungXeMay2019.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dathangtructuyen
    {
        public string Madh { get; set; }
        public string Makh { get; set; }
        public string Masp { get; set; }
        public string Tinhtrangsp { get; set; }
        public int Soluongsp { get; set; }
        public string Loaihinhtt { get; set; }
        public System.DateTime Ngaygiomuahang { get; set; }
        public string Diachigh { get; set; }
        public string Diachikh { get; set; }
        public int SDTkh { get; set; }
        public string Emailkh { get; set; }
    }
}
