//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuTungXeMay2019.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuanTriVien
    {
        public int id { get; set; }
        public string Ho { get; set; }
        public string Ten { get; set; }
        public int SDT { get; set; }
        public string Chucvu { get; set; }
    }
}
