//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuTungXeMay2019.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sanpham
    {
        public int id { get; set; }
        public string Tensp { get; set; }
        public string Loaisp { get; set; }
        public int Gia { get; set; }
        public int Soluong { get; set; }
        public string Xuatxu { get; set; }
        public string Chitietsp { get; set; }
        public string Nhasx { get; set; }
        public string Nhacungcap { get; set; }
        public byte[] Hinhanh { get; set; }
    }
}
